---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

dataSource:
#    logSql: true   # 如果需要使用并查看 sql ，请打开此注释
    pooled: true
    dbCreate: ''
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: rishiqing-beta-old-user
    password: rsQcReate640321
    url: jdbc:mysql://rm-2zen2a9e3l24p17i7fo.mysql.rds.aliyuncs.com:3306/rishiqing_beta_old?autoReconnect=true&characterEncoding=utf-8&useSSL=false
    properties:
        maxActive: -1
        minEvictableIdleTimeMillis: 1800000
        timeBetweenEvictionRunsMillis: 1800000
        numTestsPerEvictionRun: 3
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: true
        validationQuery: SELECT 1

---
foo:
    bar:
        hello: 'hello'
---
locations: ['file:myconf.yml']
---
grails:
    profile: web
    codegen:
        defaultPackage: rishiqing.notice.server
    spring:
        transactionManagement:
            proxies: false
    config:
        locations: ['classpath:server-config.properties']
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false

---
server:
    port: 8177
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

# server自定义参数区域
fetchMinute: 60 # fetch every 10 minutes
preFetchMinute: 2 # 查询job提前查询几分钟的数据
soundURL: Umbriel.aiff
androidSoundURL: android.resource://com.rishiqing/raw/alarm2

#beta
qywxUrl: https://qywx-beta.rishiqing.com
qywxPageUri: /qywxbackwebapp/index.html
qywxInterfaceUri: /qywxbackauth

#官网
#qywxUrl: https://qywx.rishiqing.com
#qywxPageUri: /qywxbackwebapp/index.html
#qywxInterfaceUri: /qywxbackauth